- name: Try to create a VM in proxmox
  block:
    - name: Choose pve node
      ansible.builtin.set_fact:
        proxmox_pve_node: "{{ host_node | default(proxmox.nodes | random) }}" 
    
    # TODO autodiscover the pve node when the vm already exists

    - name: Setup VM in proxmox
      throttle: 1
      community.general.proxmox_kvm:
        clone: "{{ host_clone }}"
        name: "{{ host_name }}"
        newid: "{{ host_vm_id | default(omit) }}"
        memory: "{{ host_memory | default('4096') }}"
        cores: "{{ host_cores | default('2') }}"
        storage: "{{ host_storage | default(omit) }}"
        nameservers: "{{ host_nameservers | default(omit) }}"
        searchdomains: "{{ host_searchdomains | default(omit) }}"
        timeout: "{{ host_timeout | default(300) }}"
        node: "{{ proxmox_pve_node }}"
        onboot: "{{ host_onboot }}" 
        full: "{{ host_full_clone | default(false) }}"
        vmid: "{{ host_vmid | default(omit) }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        state: present
      register: created_vm

    - name: Sleep for 60 seconds
      ansible.builtin.wait_for:
        timeout: 60 
      when: created_vm.changed
      
    - name: Update hardwarde parameters
      community.general.proxmox_kvm:
        name: "{{ host_name }}"
        timeout: "{{ proxmox.api.timeout | default(300) }}"
        node: "{{ proxmox_pve_node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        memory: "{{ host_memory | default('4096') }}"
        cores: "{{ host_cores | default('2') }}"
        kvm: "{{ kvm_hardware_virt | default(omit) }}"
        update: true
      ignore_errors: true
      register: proxmox_hardware_update

    - name: Update drive configuration
      ansible.builtin.import_tasks: add_storage.yml
      when: host_disks is defined

    - name: Configure cloud init parameters
      community.general.proxmox_kvm:
        name: "{{ host_name }}"
        timeout: "{{ proxmox.api.timeout | default(300) }}"
        node: "{{ proxmox_pve_node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        autostart: "{{ host_autostart | default(true)  }}"
        ciuser: "{{ host_user }}"
        cipassword: "{{ host_password }}"
        sshkeys: "{{ host_ssh_keys | default(omit) }}"
        net:
          net0: "virtio,bridge={{ host_bridge | default('vmbr0') }},tag=77" 
        ipconfig:
          ipconfig0: "ip={{ host_ipv4 }}/{{ host_subnet }},gw={{ host_gateway }}" 
        update: true
      when: created_vm.changed
      register: proxmox_configure_cloud_init
    
    - name: Start VM in proxmox
      community.general.proxmox_kvm:
        name: "{{ host_name }}"
        timeout: "{{ proxmox.api.timeout | default(300) }}"
        node: "{{ proxmox.nodes | random }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        state: started
      register: proxmox_vm_started

    - name: Take a snapshot of the vm
      ansible.builtin.import_tasks: add_snapshot.yml
      when: host_snapshot

    - name: Register hostname at DNS server
      ansible.builtin.include_role:
        name: powerdns
        tasks_from: create_record
      when: host_nameservers is defined

    - name: Wait for the machine to come online
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 600
      when: created_vm.changed

    - name: Wait for ssh to become available
      ansible.builtin.wait_for:
        port: 22
        sleep: 10
        host: "{{ host_ipv4 }}"
    
    - name: Write the new VM instance host key to known hosts
      connection: local
      ansible.builtin.shell: "ssh-keyscan -H {{ host_ipv4 }} >> ~/.ssh/known_hosts"
      when: created_vm.changed
  rescue:
    - name: Remove VM in proxmox
      community.general.proxmox_kvm:
        name: "{{ host_name }}"
        node: "{{ proxmox_pve_node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        state: restarted 
    - name: Remove VM in proxmox
      community.general.proxmox_kvm:
        name: "{{ host_name }}"
        node: "{{ proxmox_pve_node }}"
        api_user: "{{ proxmox.api.user.full_name }}"
        api_token_id: "{{ proxmox.api.token.id }}"
        api_token_secret: "{{ proxmox.api.token.secret }}"
        api_host: "{{ proxmox.api.host }}"
        force: true
        state: absent 
      when: host_remove_failed
