- name: Create complete torrent directory 
  ansible.builtin.file:
    path: "/home/{{ host_user }}/plex/data/torrents/complete"
    mode: '0777'
    state: directory

- name: Create incomplete torrent directory 
  ansible.builtin.file:
    path: "/home/{{ host_user }}/plex/data/torrents/incomplete"
    mode: '0777'
    state: directory

- name: Start watchtower docker container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    env:
      TZ: Europe/Amsterdam
      PUID: '1000'
      PGID: '1000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: "always"
    state: started

- name: Start gluetun docker container
  community.docker.docker_container:
    name: gluetun 
    image: qmcgaw/gluetun
    env:
      TZ: Europe/Amsterdam
      SERVER_COUNTRIES: 'Netherlands'
      OPENVPN_USER: "{{ openvpn_user }}"
      OPENVPN_PASSWORD: "{{ openvpn_password }}"
      VPN_SERVICE_PROVIDER: 'nordvpn'
    devices:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - 'NET_ADMIN'
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart_policy: "unless-stopped"
    state: started

- name: Configure sabnzb
  ansible.builtin.template:
    src: qBittorrent.conf.j2
    dest: "/home/{{ host_user }}/config/qbittorrent/config/qBittorrent.conf"
  become_user: "{{ host_user }}" 
  become: false

- name: Start Qbittorrent Docker container
  community.docker.docker_container:
    name: qbittorrent 
    image: ghcr.io/hotio/qbittorrent
    env:
      TZ: Europe/Amsterdam
      PUID: '1000'
      PGID: '1000'
      umask: '002'
    volumes:
      - "/home/{{ host_user }}/config/qbittorrent:/config"
      - "/home/{{ host_user }}/plex/data/torrents:/data/torrents/"
    restart_policy: "unless-stopped"
    network_mode: container:gluetun
    state: started