host_vm_id: 704
host_name: qbittorrent 
host_zone: gijsentius.org
host_gateway: 192.168.178.1
host_ipv4: 192.168.178.222
host_nameservers: 
  - 192.168.178.53
host_subnet: 24
host_subnet_cidr: '192.168.178.0/24'
host_clone: debian-12-bookworm-cloudinit-template
host_memory: '1024'
host_cores: '1'
host_fileshares:
  - remote_path: /mnt/share/plex/data
    local_path: /home/gijs/plex/data
    host: nfs.gijsentius.org
vpn_wireguard_private_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33653438633261383134326565636432306632636561396664373363316362386635326538373232
    3232623732326336373664383263303233343564393936650a346538393937373662306661363765
    65633866346166323732643066626636643362396131643030663764303731373338333731393561
    6233663436373864380a656562633135383365613435666166323430303133616365346236623062
    65616663336533616439336563613039323663356236343964323434376635306335353765383938
    3061386230396530323165306534633866363161396435623834
vpn_wireguard_addresses: 10.14.0.2/16
qbittorrent_download_dir: /data/torrents/complete
qbittorrent_temp_dir: /data/torrents/incomplete
qbittorrent_gui_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30373035363264303666306133663834666363646330346665636133376634336636623866346363
    6266626630303064633931336130623331363739333166320a306534373632303133633030376265
    36303461316263666137386537316636366264323730366663653730326432326535346534303431
    6335333331346136640a363432623765363862306433343136343063626266346665346165353031
    37386539326530326334326663366462393562383935333239633734653837316135663466613636
    39383937376264633739303166336132323865646163313566396164366231303631646463316663
    35353535343235336266396431656330623839643862313161343862353162306336663430643836
    61613131336330393631633637356331376431386431303862616335636233626436373839373930
    39656161646134313536376262336137663430623261666666306334383863363037353831313263
    3436313465373333646666393264356232323632353731653432
