- name: Configure ssh key for {{ inventory_hostname }}
  ansible.builtin.import_tasks: configure_access.yml 

- name: Configure DNS for {{ inventory_hostname }}
  ansible.builtin.import_tasks: configure_dns.yml
  become: true
  when: host_nameservers is defined

- name: Configure nfs mounts for {{ inventory_hostname }}
  include_role:
    name: nfs
  when: host_fileshares is defined