- name: Populate service facts
  service_facts:

- name: Create rke directory
  ansible.builtin.file:
    state: directory
    path: /etc/rancher/rke2 

- name: Create config yaml from template 
  ansible.builtin.template:
    src: server-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml 

- name: Download RKE2 install script 
  ansible.builtin.get_url:
    url: https://get.rke2.io
    validate_certs: false
    dest: "{{ rancher.install_dir | default('/tmp') }}/install.sh"
    mode: 0755
  when: '"rke2-server" not in services'

- name: Install RKE2 on server node
  ansible.builtin.command: "{{ rancher.install_dir | default('/tmp') }}/install.sh"
  when: '"rke2-server" not in services'

- name: Start RKE2 server service  
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: rke2-server

- name: 'Create PATH and add rancher utilities'
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'PATH="/var/lib/rancher/rke2/bin/"'
    insertafter: EOF
  when: lookup('file', '/etc/environment') is not search('^\s*PATH\s*=')

- name: 'Add rancher utilities to PATH'
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: 'PATH=(["])((?!.*?/var/lib/rancher/rke2/bin/).*?)(["])$'
    line: 'PATH=\1\2:/var/lib/rancher/rke2/bin/\3'
    backrefs: yes
