caddy_servers:
  - server: rancher.gijsentius.org
    hosts:
      - "rancher-server-1.gijsentius.org"
      - "rancher-agent-1.gijsentius.org"
      - "rancher-agent-2.gijsentius.org"
      - "rancher-agent-3.gijsentius.org"
    port: 443
    protocol: https
  - server: plex.gijsentius.org
    hosts: [plex.gijsentius.org]
    port: 32400
    protocol: http
  - server: sonarr.gijsentius.org
    hosts: [plex.gijsentius.org]
    port: 8989
    protocol: http
  - server: radarr.gijsentius.org
    hosts: [plex.gijsentius.org]
    port: 7878
    protocol: http
  - server: overseerr.gijsentius.org
    hosts: [plex.gijsentius.org]
    port: 5055
    protocol: http
  - server: prowlarr.gijsentius.org
    hosts: [plex.gijsentius.org]
    port: 9696
    protocol: http
  - server: audiobooks.gijsentius.org
    hosts: [audiobooks.gijsentius.org]
    port: 13378
    protocol: http
      # - server: sabnzb.gijsentius.org
      #   hosts: [sabnzb.gijsentius.org]
      #   port: 8080
      #   protocol: http
      # - server: qbittorrent.gijsentius.org
      #   hosts: [qbittorrent.gijsentius.org]
      #   port: 8080
      #   protocol: http
  - server: dc.gijsentius.org
    hosts: [192.168.178.69]
    port: 8006
    protocol: https
    self_signed: true
  - server: vault.gijsentius.org
    hosts: [vault.gijsentius.org]
    port: 8080
    protocol: http
